// WIP, generated by Gemini

// Define the 1x1 wireless water cable
const waterCable = extend(PowerNode, "water-power-cable", {
    // Structural configurations
    size: 1,
    health: 80,
    
    // Power network parameters
    outputsPower: true,     // Allows the block to supply power
    consumesPower: false,   // Does not consume power itself
    
    // CRITICAL: Prevents power nodes from creating laser links to this block
    connectedPower: false,  //
    
    // Allows the block to naturally touch and transmit power to adjacent touching blocks
    conductivePower: true,  //
    
    // Placement rules for Deep Water
    floating: true,
    placeableLiquid: true,
});

// CRITICAL: Filter connection targets so it only links to itself
waterCable.entityType = () => extend(PowerNode.PowerNodeEntity, {
    canConnectTo(other) {
        // Only allow connection if the other block is exactly this same cable type
        return other.block === waterCable;
    }
});

// Category and build costs
waterCable.category = Category.power;
waterCable.buildVisibility = BuildVisibility.shown;
waterCable.requirements = ItemStack.with(
    Items.copper, 5,
    Items.lead, 3
);
